const weaponCreatorData = {
  weapons: [
    {
      id: "m4a1",
      name: "M4A1",
      caliber: "5.56x45mm NATO",
      weaponType: "Assault Rifle",
      fireMode: "Single / Auto",
      manufacturer: "Colt",
      imageUrl: "https://gray-zone-warfare.fandom.com/wiki/Special:FilePath/M4A1%20inspect.png",
      description:
        "The M4A1 is a full-auto carbine built on the M4 platform, chambered in 5.56x45mm NATO. Favored for its versatility, reliability, and wide availability of attachments.",
      magStatus: { current: 30, max: 30 },
      baseStats: {
        weightKg: 3.299,
        accuracyMoa: 4.27,
        fireRatePercent: 5.5,
        recoilControl: 15.1,
        muzzleDeviceEfficiency: 6.0,
        muzzleVelocity: -0.5,
        ergonomics: 23.7,
        reloadSpeed: 1.0,
        fireRateRpm: 800,
      },
      slots: [
        {
          id: "buffer-tube",
          label: "Buffer Tube",
          options: [
            { id: "none",             name: "None (Empty)",          stats: {} },
            { id: "m4-buffer-m4",     name: "M4 Buffer Tube",        stats: {} },
            { id: "m4-buffer-m4-fde", name: "M4 Buffer Tube (FDE)",  stats: {} },
            { id: "m4-buffer-cqa1",   name: "CQ A1 Buffer Tube",     stats: {} },
          ],
          selected: "m4-buffer-m4",
        },
        {
          id: "hand-guard",
          label: "Hand Guard",
          options: [
            { id: "none",              name: "None (Empty)",                   stats: {} },
            { id: "m4-hg-dd-mk18",     name: "DD MK18 RIS II Rail System",    stats: {} },
            { id: "m4-hg-dd-omega",    name: "DD Omega Rail 7.0",             stats: {} },
            { id: "m4-hg-mlok-slim",   name: "M-LOK Slim Handguard",          stats: {} },
            { id: "m4-hg-m4-carbine",  name: "M4 Carbine Handguard",          stats: {} },
          ],
          selected: "none",
        },
        {
          id: "upper-receiver",
          label: "Upper Receiver",
          options: [
            { id: "none",           name: "None (Empty)",         stats: {} },
            { id: "m4-rec-m4",      name: "M4 Upper Receiver",    stats: {} },
            { id: "m4-rec-m16a1",   name: "M16A1 Upper Receiver", stats: {} },
            { id: "m4-rec-cqa1",    name: "CQ A1 Upper Receiver", stats: {} },
          ],
          selected: "m4-rec-m4",
        },
        {
          id: "pistol-grip",
          label: "Pistol Grip",
          options: [
            { id: "none",               name: "None (Empty)",                          stats: {} },
            { id: "m4-grip-cqa1",       name: "Norinco CQA1 Pistol Grip",             stats: {} },
            { id: "m4-grip-miad",       name: "MIAD Pistol Grip",                     stats: {} },
            { id: "m4-grip-torque",     name: "Torque Pistol Grip",                   stats: {} },
            { id: "m4-grip-moe",        name: "MOE Pistol Grip",                      stats: {} },
            { id: "m4-grip-moe-fde",    name: "MOE Pistol Grip (FDE)",                stats: {} },
            { id: "m4-grip-dd-milspec", name: "DD Enhanced AR Pistol Grip (MILSPEC)", stats: {} },
            { id: "m4-grip-dd",         name: "DD Enhanced AR Pistol Grip",           stats: {} },
            { id: "m4-grip-dd-black",   name: "DD Enhanced AR Pistol Grip (Black)",   stats: {} },
          ],
          selected: "m4-grip-cqa1",
        },
        {
          id: "magazine",
          label: "Magazine",
          options: [
            { id: "none",                name: "None (Empty)",                               stats: {} },
            { id: "m4-mag-stanag-30",    name: "STANAG 5.56x45mm 30-Round Magazine",        stats: {} },
            { id: "m4-mag-stanag-20",    name: "STANAG 5.56x45mm 20-Round Magazine",        stats: {} },
            { id: "m4-mag-pmag-30",      name: "PMAG 5.56x45mm 30-Round Magazine",          stats: {} },
            { id: "m4-mag-pmag-30-fde",  name: "PMAG 5.56x45mm 30-Round Magazine (FDE)",   stats: {} },
            { id: "m4-mag-dd-32",        name: "DD 5.56x45mm 32-Round Magazine",            stats: {} },
            { id: "m4-mag-ati-s60",      name: "ATI S60 5.56x45mm 60-Round Magazine",       stats: {} },
          ],
          selected: "m4-mag-stanag-30",
        },
        {
          id: "charging-handle",
          label: "Handle",
          options: [
            { id: "none",             name: "None (Empty)",                       stats: {} },
            { id: "m4-ch-gi",         name: "Standard GI Charging Handle",       stats: {} },
            { id: "m4-ch-cqa1",       name: "CQ A1 Charging Handle",             stats: {} },
            { id: "m4-ch-f1",         name: "F1 Charging Handle",                stats: {} },
            { id: "m4-ch-grip-n-rip", name: "AR-15 GRIP-N-RIP Charging Handle",  stats: {} },
            { id: "m4-ch-sch",        name: "SCH 5.56 Charging Handle",          stats: {} },
            { id: "m4-ch-sch-ddc",    name: "SCH 5.56 Charging Handle (DDC)",    stats: {} },
            { id: "m4-ch-supreme",    name: "AR-15 Supreme Charging Handle",     stats: {} },
          ],
          selected: "m4-ch-gi",
        },
        {
          id: "barrel",
          label: "Barrel",
          options: [
            { id: "none",                 name: "None (Empty)",         stats: {} },
            { id: "m4-barrel-14-5",       name: "M4A1 14.5\" Barrel",  stats: {} },
            { id: "m4-barrel-16",         name: "M4A1 16\" Barrel",    stats: {} },
            { id: "m4-barrel-cqa1-10-4",  name: "CQ A1 10.4\" Barrel", stats: {} },
            { id: "m4-barrel-m16a1-20",   name: "M16A1 20\" Barrel",   stats: {} },
          ],
          selected: "m4-barrel-14-5",
        },
        {
          id: "bottom-mid-rail",
          label: "Bottom Mid Rail",
          options: [
            { id: "none",              name: "None (Empty)",              stats: {} },
            { id: "m4-bmr-rvg",        name: "RVG Vertical Foregrip",     stats: {} },
            { id: "m4-bmr-angled",     name: "Angled Foregrip",           stats: {} },
            { id: "m4-bmr-m3x-light",  name: "M3X Tactical Illuminator",  stats: {} },
          ],
          selected: "none",
        },
        {
          id: "left-rail",
          label: "Left Rail",
          options: [
            { id: "none",             name: "None (Empty)",        stats: {} },
            { id: "m4-lr-flashlight", name: "Tactical Flashlight", stats: {} },
            { id: "m4-lr-laser",      name: "AN/PEQ-15 Laser",     stats: {} },
          ],
          selected: "none",
        },
        {
          id: "right-rail",
          label: "Right Rail",
          options: [
            { id: "none",             name: "None (Empty)",        stats: {} },
            { id: "m4-rr-flashlight", name: "Tactical Flashlight", stats: {} },
            { id: "m4-rr-laser",      name: "AN/PEQ-15 Laser",     stats: {} },
          ],
          selected: "none",
        },
        {
          id: "rail",
          label: "Rail",
          options: [
            { id: "none",              name: "None (Empty)",          stats: {} },
            { id: "m4-rail-picatinny", name: "Picatinny Rail Segment", stats: {} },
            { id: "m4-rail-mlok",      name: "M-LOK Rail Segment",    stats: {} },
          ],
          selected: "none",
        },
        {
          id: "upper-mid-rail",
          label: "Upper Mid Rail",
          options: [
            { id: "none",           name: "None (Empty)",              stats: {} },
            { id: "m4-umr-backup",  name: "Backup Iron Sight (Front)", stats: {} },
            { id: "m4-umr-riser",   name: "Rail Riser",                stats: {} },
          ],
          selected: "none",
        },
        {
          id: "bottom-front-rail",
          label: "Bottom Front Rail",
          options: [
            { id: "none",            name: "None (Empty)",   stats: {} },
            { id: "m4-bfr-stubby",   name: "Stubby Foregrip", stats: {} },
            { id: "m4-bfr-light",    name: "Weapon Light",    stats: {} },
          ],
          selected: "none",
        },
        {
          id: "rear-sight",
          label: "Rear Sight",
          options: [
            { id: "none",               name: "None (Empty)",               stats: {} },
            { id: "m4-rs-mbus",         name: "MBUS Rear Sight",            stats: {} },
            { id: "m4-rs-troy",         name: "Troy BattleSight Rear",      stats: {} },
            { id: "m4-rs-carry-handle", name: "A2 Carry Handle Rear Sight", stats: {} },
          ],
          selected: "none",
        },
        {
          id: "collimator",
          label: "Collimator",
          options: [
            { id: "none",            name: "None (Empty)",       stats: {} },
            { id: "m4-col-aimpoint", name: "Aimpoint Micro T-2", stats: {} },
            { id: "m4-col-eotech",   name: "EOTech XPS3",        stats: {} },
            { id: "m4-col-mro",      name: "Trijicon MRO",       stats: {} },
            { id: "m4-col-srs",      name: "Trijicon SRS",       stats: {} },
          ],
          selected: "none",
        },
        {
          id: "magnifier",
          label: "Magnifier",
          options: [
            { id: "none",         name: "None (Empty)",          stats: {} },
            { id: "m4-mag-g33",   name: "EOTech G33 Magnifier",  stats: {} },
            { id: "m4-mag-g43",   name: "Aimpoint 3x Magnifier", stats: {} },
          ],
          selected: "none",
        },
        {
          id: "muzzle-device",
          label: "Muzzle Device",
          options: [
            { id: "none",             name: "None (Empty)",                  stats: {} },
            { id: "m4-muz-a2",        name: "A2 Flash Hider",               stats: {} },
            { id: "m4-muz-surefire",  name: "Surefire SOCOM 556 Suppressor", stats: {} },
            { id: "m4-muz-strike",    name: "Strike Industries J-COMP",     stats: {} },
            { id: "m4-muz-sf-mini",   name: "Surefire SOCOM Mini Brake",    stats: {} },
          ],
          selected: "none",
        },
        {
          id: "magnifier-mount",
          label: "Magnifier Mount",
          options: [
            { id: "none",          name: "None (Empty)",             stats: {} },
            { id: "m4-mm-larue",   name: "LaRue QD Pivot Mount",    stats: {} },
            { id: "m4-mm-unity",   name: "Unity Tactical FAST Mount", stats: {} },
          ],
          selected: "none",
        },
        {
          id: "gas-block",
          label: "Gas Block",
          options: [
            { id: "none",             name: "None (Empty)",                       stats: {} },
            { id: "m4-gb-low-profile","name": "Low Profile Gas Block",            stats: {} },
            { id: "m4-gb-dd-fixed",   name: "DD Fixed Front Sight Gas Block",    stats: {} },
            { id: "m4-gb-gbrs",       name: "GBRS Group Gas Block",              stats: {} },
          ],
          selected: "none",
        },
      ],
    },
  ],
};
