const missionGivers = [
  {
    id: "handshake",
    name: "Handshake",
    imageUrl: "https://gray-zone-warfare.fandom.com/wiki/Special:FilePath/HandshakePortraitTasks.png",
    missions: [
      "First Recon",
      "Little Bird Down",
      "Reclamation",
      "Rat's Nest",
      "Radio Silence",
      "Helping Hand",
      "Restoring Order",
      "First Hit",
      "Left Behind",
      "The Shadow over Ban Pa",
      "Combat Sweep VII",
      "Muddy Buddy",
      "The Liberator",
      "The Ban Pa Horror",
      "Fresh Meat",
      "The Great Escape",
      "Combat Sweep IX",
      "Problem Solver",
      "Combat Sweep IV",
      "Domesticated Rat",
      "Restructuring",
      "One Shot, One Kill",
      "Up to Snuff",
      "Business or Pleasure",
      "Mr. Nice Guy",
      "Combat Sweep VI",
      "Departure",
      "I went, I saw, I conquered",
      "Plan B",
      "Chopping Blocks",
      "Combat Sweep II",
      "Irrefusable Offer",
      "Sisyphus",
      "Mire Job",
      "King of the Crossroads",
      "Missing Children",
      "Revolutionary Road",
      "Combat Sweep",
      "The Cleaner",
      "Radio Star",
      "Moonlighting II",
      "Unattainable Luxury",
      "UNLRA",
      "Troll Bridge",
      "Combat Sweep VIII",
      "Trifle",
      "Hacker",
      "New Neighbors",
      "Hustling the Hustler",
      "Combat Sweep III",
      "Fort Narith Stroll",
      "True Grit",
      "Big Fish",
      "Terminal Initiative"
    ]
  },
  {
    id: "gunny",
    name: "Gunny",
    imageUrl: "https://gray-zone-warfare.fandom.com/wiki/Special:FilePath/GunnyPortraitTasks.png",
    missions: [
      "Cache Retrieval",
      "Leave No Man Behind",
      "Hoarder",
      "Street Spotter",
      "Paranoia Agent",
      "Unresponsive",
      "Medical Detective",
      "Cache Report VI",
      "Cache Report VII",
      "Supernatural",
      "From the Sky",
      "Lost Girl",
      "They Are Everywhere",
      "Cache Report IX",
      "Cache Report VIII",
      "Cache Report IV",
      "Nicked Shipment",
      "Guns & Ammo",
      "Freedom Fighter",
      "Fire and Water",
      "Questionable Shipment",
      "Fuel Shortage",
      "Propaganda Problems",
      "Cache Report III",
      "Last Farewell",
      "Under Our Noses",
      "Goods Hunting",
      "Needle in a Jungle",
      "Snooper",
      "Like a Boss - Broker's M9A1",
      "Like a Boss - Kaptei's Glock 17",
      "Chameleon - DDM4 (PL)",
      "Chameleon - Mossberg 590 (RT)",
      "The Negotiator",
      "Sunken Bird",
      "Cache Report",
      "No Bullshit III",
      "Expansion",
      "The Rebel Path",
      "Cache Report V",
      "Know Your Enemy",
      "A Single Drop",
      "Last Farewell II",
      "The Stand",
      "The Lull",
      "Observation Duty",
      "Wanted Man",
      "Neighborly Help",
      "Cache Report II",
      "No Bullshit"
    ]
  },
  {
    id: "labrat",
    name: "Labrat",
    imageUrl: "https://gray-zone-warfare.fandom.com/wiki/Special:FilePath/LabratPortraitTasks.png",
    missions: [
      "Meds Wanted",
      "Emergency Response",
      "Unlisted Flight",
      "Echoes of Exposure",
      "Cryptic Signals",
      "Schadenfreude",
      "Cult Business",
      "The Last Broadcast",
      "Cryptic Signals VII",
      "The Trickster",
      "Interrupted Aid",
      "Cryptic Signals II",
      "Escort II",
      "The Most Dangerous Game",
      "Lethal Dose",
      "Exodus",
      "Escort",
      "Lab Assistant III",
      "Cryptic Signals V",
      "Lab Assistant",
      "False Positive",
      "Cryptic Signals VI",
      "Postman Rings Twice",
      "UNprotected",
      "Firestarter",
      "Elderly Delivery",
      "A Voice from the Stars",
      "Mystery Machines",
      "Cryptic Signals III",
      "Memory Leak",
      "Cryptic Signals VIII",
      "Too Close to the Sun",
      "Spit Out the Poison",
      "Up the Stream",
      "Duty to the Country",
      "Seeker of Change",
      "Cryptic Signals IV",
      "Crumb Collector",
      "Ripper",
      "The Runaway",
      "So Close",
      "Cryptic Signals IX"
    ]
  },
  {
    id: "artisan",
    name: "Artisan",
    imageUrl: "https://gray-zone-warfare.fandom.com/wiki/Special:FilePath/ArtisanPortraitTasks.png",
    missions: [
      "Tools of the Trade",
      "Secret Compassion",
      "Lost and Found",
      "Silent Village",
      "No Casualties",
      "Last Flight",
      "Letter From Beyond",
      "Mercenary Delivery Service III",
      "Mercenary Delivery Service",
      "Sunken Hope",
      "Deep Waters",
      "Don't Speak",
      "Snow White",
      "Handyman",
      "Last Letter",
      "Draw No Bet",
      "Chameleon - SVD Dragunov (SW)",
      "Chameleon - AKMN (JC)",
      "Like a Boss - Colonel's Type 51",
      "Like a Boss - Naga's Type 51",
      "Freedom for All",
      "Mercenary Delivery Service II",
      "Missing Colleague II",
      "When a Tree Falls",
      "Garbage Disposal",
      "Prisoner 23",
      "Missing Colleague",
      "Evacuation Question",
      "Artisan's List",
      "Artisan's List II",
      "The Call of Phi Pa Mum",
      "Lost Hope",
      "The Mistress",
      "At the Mounds of Madness",
      "Girls Just Wanna Have Fun",
      "Crime Doesn't Pay"
    ]
  },
  {
    id: "turncoat",
    name: "Turncoat",
    imageUrl: "https://gray-zone-warfare.fandom.com/wiki/Special:FilePath/TurncoatPortraitTasks.png",
    missions: [
      "Letters from Lamang",
      "Warm Welcome",
      "Repossession V",
      "Repossession VIII",
      "Not On My Watch",
      "Repossession II",
      "Repossession III",
      "Double Agent",
      "Friendly Conveyance",
      "Dishonest Practices",
      "The Snitch",
      "Narcotic Bargain",
      "The Value of Sharing",
      "One Man's Trash",
      "Friendly Suggestion",
      "Repossession IX",
      "Leeches",
      "Free Real Estate",
      "Repossession",
      "Downsizing",
      "Dragonslayer",
      "In the Right Hands",
      "Family Heirloom",
      "Double Exposure",
      "A Small Favor",
      "Name Your Poison",
      "Repossession VI",
      "Cutting Ties",
      "Repossession IV",
      "No Questions Asked",
      "Academic Interest",
      "Local Golf Star",
      "A Tiding of Magpies",
      "Delayed Package",
      "In the Trenches",
      "Like a Boss - Firebrand's AKS-74U",
      "Like a Boss - Buran's AK-74N",
      "Freedom Fighter Hunt",
      "Repossession VII",
      "Final Liberation"
    ]
  },
  {
    id: "banshee",
    name: "Banshee",
    imageUrl: "https://gray-zone-warfare.fandom.com/wiki/Special:FilePath/BansheePortraitTasks.png",
    missions: [
      "Ink Saver",
      "Livestock",
      "Mysterious Justice III",
      "Atrocity Probe",
      "Mysterious Justice II",
      "Mysterious Justice",
      "Lamang Connection",
      "What Was Left",
      "Baked",
      "Sanctioned Exploitation",
      "Buried on Paper",
      "Mysterious Justice IX",
      "State of Weapon Shipment",
      "No Escape",
      "EOD",
      "Deal of the Century",
      "Jets'n'Marks",
      "Mysterious Justice VIII",
      "Sunny Skies",
      "Mysterious Justice IV",
      "Noble Powder",
      "Crash",
      "Dirt Digger",
      "Felony and Punishment",
      "Mysterious Justice V",
      "Timber",
      "Mysterious Justice VII",
      "Harvest Moon",
      "Chameleon - M14 (BH)",
      "Chameleon - M700 (GC)",
      "Chameleon - MP7A2 (SC)",
      "Chameleon - SIG MCX (GN)",
      "Like a Boss - Yen's M700",
      "Unstable Meeting",
      "Mysterious Justice VI"
    ]
  },
  {
    id: "vulture",
    name: "Vulture",
    imageUrl: "https://gray-zone-warfare.fandom.com/wiki/Special:FilePath/VulturePortraitTasks.png",
    missions: [
      "Like a Boss - Grin's 1911 C",
      "Like a Boss - Viper's 1911 C",
      "Chameleon - AK-308 (HT)"
    ]
  }
];
